package org.jedi_bachelor.strategy.model.effects;

public enum FeaturesEnum {
    EFFECTIVITY_CIVIL_INDUSTRY,
    EFFECTIVITY_MILITARY_INDUSTRY,
    EFFECTIVITY_FARMS,
    EFFECTIVITY_OIL_REFINERIES,
    PROFITABILITY,

    ATTACK_EFFORT,
    DEFENCE_EFFORT,

    SPEED_BUILD
}
